# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- script: |
    echo Hello, world!
    ls -l
  displayName: 'lets get started!'

- script: |
    echo try install cordova...
    npm install -g cordova
    cordova --version
  displayName: 'Cordova Install'

- script: npm install -g ios-deploy
  displayName: 'ios-deploy'

- script: gem install cocoapods
  displayName: 'CocoaPods install'

- script: cordova prepare
  displayName: 'Cordova Prepare'

- script: ls -l
  displayName: 'lists after prepare'

- script: cordova requirements
  displayName: 'Cordova Requirements'

- script: cordova build ios --debug --emulator --verbose
  displayName: 'Build iOS Emulator'

- script: ls -l
  displayName: 'lists build ios emu'

# - task: CopyFiles@2
#   inputs:
#     contents: |
#       platforms/ios/build/emulator/*.app
#       platforms/ios/build/emulator/*.dSYM
#     targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    contents: '**/?(*.app|*.dSYM)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- script: |
    pwd
    echo $(Build.ArtifactStagingDirectory)
    echo $(Build.SourcesDirectory)
    ls -lh platforms/ios/build/emulator
    ls -lh '$(Build.ArtifactStagingDirectory)'
  displayName: 'wheres da files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
